# Generated by Django 5.2.5 on 2025-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usuario_email_usuario_endereco_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
