# Generated by Django 5.2.5 on 2025-08-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usuario_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='status',
        ),
    ]
