# Generated by Django 5.2.5 on 2025-08-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_servico_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.servico')),
            ],
        ),
    ]
