# Generated by Django 5.2.5 on 2025-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='Agendado', max_length=20),
        ),
    ]
