# Generated by Django 5.2.5 on 2025-08-12 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_agendamento', to='home.usuario'),
        ),
    ]
